### ISSUE TITLE
Not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by AVillalonga** [Borecjeborec1/LepikJS#10]
The package does not seem to work on my Ubuntu 22.04.2.
I have installed both python modules and trying execute the script bellow

```js
const lepik = require('lepikjs');

lepik.on("mouseMove", (data) => {
    console.log(data)
})

lepik.getMousePosition().then(console.log) // <<== !!! WORKED !!!

lepik.mouseMove(804, 332)
lepik.mouseClick("left")
lepik.mouseDoubleClick("left")

setTimeout(() => {
    lepik.close()
}, 20000)
```

I only got the mouse position from line 6 (`{ x: 600, y: 100 }`) and nothing else.
Plus 2 files are created with administrator rights.

![Screenshot from 2023-05-03 01-24-27](https://user-images.githubusercontent.com/37465521/235806049-4e3bd0e3-a3ce-43ca-995b-cb52bb3fa8f7.png)
![Screenshot from 2023-05-03 01-26-14](https://user-images.githubusercontent.com/37465521/235806261-50c4cafa-9298-47e5-938c-342e2f65dc74.png)

thank you in advance for the help that will be given

**Comment by Borecjeborec1** [comment]
Hi!

I have made some research and it seems that the lepikjs package is not working as expected on some Ubuntu versions.

As you mentioned, the package relies on the python modules for mouse and keyboard input, which are the reason why it's not working as expected. _(probably ;D)_

I've also found that there are some issues with the mouse and keyboard python modules on Ubuntu versions.

> From  https://stackoverflow.com/questions/72808902/automated-mouse-clicking-in-python-ubuntu-18-04-lts.
>
> Do you run Linux without X server? It is unusual - and most modules which use mouse need X server because they use functions built-in in X server - they send mouse event to X server and it sends it to active window.

You can try using a very simple python script relying only on the mouse module itself.
Here is the code:
```python
import mouse

mouse.click()
```
It sounds bad, but this should not work. If it does, then the problem is somewhere else, so give it a try please.

PS:  _Not only Ubuntu version are not working, but I did not find a connection between the not-working devices yet_

Now to your seconds issue about the creation of the files with root rights.

> The __pycache__ directory is used by Python to store compiled bytecode files (*.pyc) to improve the startup time of Python programs by avoiding the need to recompile the source code every time the program is run.

This means that when Python compiles a source code file into bytecode and saves it to the __pycache__ directory, it sets the owner of the file to the user who ran the Python interpreter at the time the file was compiled. If you ran the Python interpreter with root privileges (e.g., by using sudo), then the compiled bytecode files will be owned by root.

This is because the ownership of a file is determined by the user who created the file. In this case, Python creates the compiled bytecode files as a result of running the interpreter with root privileges, so the files are owned by root.

And as long as mouse and keyboard modules require running with `sudo`, just as the lepikjs does, the `.pyc` files are created with root privileges.

**Comment by Borecjeborec1** [comment]
I can try to rebuild the app for the "not working OS's", so it does not rely on the mouse module.
But I can't say when it will be...

I will keep you updated :D

**Comment by AVillalonga** [comment]
RobotJs installation doesn't work either 😈

After some research on the ubuntu site I came across this [gui script doc](https://doc.ubuntu-fr.org/gui_scripts).
[Xnee](https://xnee.wordpress.com/) is build for GNU systems and based on [swinput](http://savannah.nongnu.org/projects/swinput) a very small library write in C (using [GPL-2.0](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html) license).

I'll try it as soon as possible if it works I should have time to implement a release for Lepik tomorrow or this weekend. GNU Systems should no longer be a problem anymore 💪

**Comment by AVillalonga** [comment]
That wasn't work with swinput because it require to have 3.3 kernel dependencies before be able to use `make install`.
Plus it require to install 2 (bison & flex) apt packages. I think it's to complicate to implement it.

BUT I try [xdotool](https://manpages.ubuntu.com/manpages/trusty/man1/xdotool.1.html) and it work perfectly ! Avaible for any X11.
I will notify you on this thread when I finish the implementation and ready to merge

🚀 Hope that it suits you 🚀

**Comment by Borecjeborec1** [comment]
Nice idea!

I have implemented the xdotool to [lepik v2.1.0+](https://www.npmjs.com/package/lepikjs). 

I know it's not ideal, but when the app is run, Lepik class checks for xdotool. If it's not installed it will install it requiring sudo permissions. (I couldn't come with a better solution)

Currently there are implemented the same methods as there were with the mouse/keyboard module. But as I checked the xdotool it has capability of much much more.

Thanks for doing the research and all the help! 💖

**Comment by Borecjeborec1** [comment]
Uhhh. Bad news...

`lepik.mouseMove` and `lepik.mouseDrag` are not working on my 32bit Kali linux. All other methods are working.

**Comment by AVillalonga** [comment]
Thank you very much ! i will try this right away <3

**Comment by KonstantinLitvin** [comment]
You could try to fix mouse module slightly https://github.com/boppreh/mouse/issues/37#issuecomment-1102803830

**Comment by Borecjeborec1** [comment]
I could, but I started working on [v3.0.0](https://github.com/Borecjeborec1/LepikJS/tree/v3.0.0), where I'd like to give up using python altogether. 

For Linux OS there is an X11 based tool called [xdotool](https://manpages.ubuntu.com/manpages/trusty/man1/xdotool.1.html), and for windows I started using powershell because it doesn't require anything extra to set up and is quite powerful.

But for the [LepikEvents](https://github.com/Borecjeborec1/lepikEvents) where I haven't really figured out the migration from python I could look more deeply inside the module. Thanks!
