### ISSUE TITLE
Inconsistent naming conventions for keypress

### ISSUE THREAD

**Issue by Antix-Development** [Borecjeborec1/LepikJS#6]
Hi, firstly I must say what a bloody fantastic "thing" you have made. Thanks for sharing it!

Naming of the windows key is however inconsistent with other naming conventions.

You have "left windows" for the left key but when pressing the left shift key it is not "left shift", instead it is just "shift", but you have "right shift" for the right shift key.

It would be great if the naming was a little more consistent so a "left windows" and "right windows" would be great.

**Comment by Borecjeborec1** [comment]
Hey there!
Again - thank you and sorry for late response.

This should be fixed with v1.5.0+
Also added more keys that can be handled.
Here is the full list:

```Javascript
let supportedKeys = ['backspace', 'tab', 'clear', 'enter', 'shift', 'ctrl', 'alt', 'pause', 'caps-lock', 'esc', 'spacebar', 'page-up', 'page-down', 'end', 'home', 'left', 'up', 'right', 'down', 'select', 'print-screen', 'insert', 'delete', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'left-windows', 'right-windows', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '*', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'num-lock', 'scroll-lock', 'left-shift', 'right-shift', 'left-ctrl', 'right-ctrl', 'left-menu', 'right-menu', 'volume-mute', 'volume-down', 'volume-up', 'next-track', 'previous-track', 'stop-media', ',', '.', 'play', 'zoom', 'clear']
```

As you suggested, the button left windows, left shift, etc. are all added. _(They are split with "-", so "left shift" is "left-shift")_
To get this full list of supportedKeys  you can use Lepik built in method **getSupportedKeys**.
```Javascript
let supportedKeys = lepik.getSupportedKeys()
```

Every single one of them should work, but didn't test them all yet.

Huge thanks for that suggestion, it is something which should be there sooner.
Closing this issue as solved with v1.5.0+
